table PROD_cmrprojreqmain
	lineageTag: 070526a1-9427-41d1-b45b-06a92b588b30

	measure 'Latest Operating Budget Date' = ```
			
			CALCULATE(
			    MAX('PROD_cmrprojreqmain'[Budget Available Date]),
			    'PROD_cmrprojreqmain'[Funding Classification] = "Operating"
			)
			
			```
		formatString: General Date
		lineageTag: c73a42f6-551b-4e81-8e41-6f1e3daddd0b

	measure 'Latest Capital Budget Date' = ```
			
			CALCULATE(
			    MAX('PROD_cmrprojreqmain'[Budget Available Date]),
			    'PROD_cmrprojreqmain'[Funding Classification] = "Capital Investment"
			)
			
			```
		formatString: General Date
		lineageTag: 20f9d31c-add3-4cc8-a732-f0a82ad58324

	measure 'Latest Operating Budget Value' = ```
			
			CALCULATE (
			    MAX ( 'PROD_cmrprojreqmain'[Budget Available] ),
			    FILTER (
			        'PROD_cmrprojreqmain',
			        'PROD_cmrprojreqmain'[Funding Classification] = "Operating"
			            && 'PROD_cmrprojreqmain'[Budget Available Date]
			                = CALCULATE (
			                    MAX ( 'PROD_cmrprojreqmain'[Budget Available Date] ),
			                    'PROD_cmrprojreqmain'[Funding Classification] = "Operating"
			                )
			    )
			)
			
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 01c7e1cc-0565-453e-a659-a03e67a1652c

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Latest Capital Budget Value' =
			
			CALCULATE (
			    MAX ( 'PROD_cmrprojreqmain'[Budget Available] ),
			    FILTER (
			        'PROD_cmrprojreqmain',
			        'PROD_cmrprojreqmain'[Funding Classification] = "Capital Investment"
			            && 'PROD_cmrprojreqmain'[Budget Available Date]
			                = CALCULATE (
			                    MAX ( 'PROD_cmrprojreqmain'[Budget Available Date] ),
			                    'PROD_cmrprojreqmain'[Funding Classification] = "Capital Investment"
			                )
			    )
			)
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: dc23d6f6-8a68-4275-a6d4-f4f010b81db7

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Total Requested - Operating' =
			
			CALCULATE(
			    SUMX(
			        PROD_cmrprojreqmain,
			        IF(
			            ISBLANK(PROD_cmrprojreqmain[par requested tpc]) || PROD_cmrprojreqmain[par requested tpc] = 0,
			            PROD_cmrprojreqmain[Estimated TPC (Cost Factored)],
			            PROD_cmrprojreqmain[par requested tpc]
			        )
			    ),
			    PROD_cmrprojreqmain[Funding Classification] = "Operating",
			    PROD_cmrprojreqmain[Request Status] <> "Cancelled"
			)
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 0c2c41fa-0352-42e8-baa2-47b9e48f9b76

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Total Requested - Capital' = ```
			
			CALCULATE (
			    SUMX (
			        PROD_cmrprojreqmain,
			        IF (
			            ISBLANK ( PROD_cmrprojreqmain[par requested tpc] ) || PROD_cmrprojreqmain[par requested tpc] = 0,
			            PROD_cmrprojreqmain[Estimated TPC (Cost Factored)],
			            PROD_cmrprojreqmain[par requested tpc]
			        )
			    ),
			    PROD_cmrprojreqmain[Funding Classification] = "Capital Investment",
			    PROD_cmrprojreqmain[Request Status] <> "Cancelled",
			    REMOVEFILTERS ( PROD_cmrprojreqmain[Funding Classification] )
			)
			
			
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 3f908cac-7968-4962-8ee5-5b645d175a98

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Total Requested - Pending' =
			
			CALCULATE (
			    SUM ( 'PROD_cmrprojreqmain'[Estimated TPC (Cost Factored)] ),
			    'PROD_cmrprojreqmain'[Funding Classification] = "Pending",
			    'PROD_cmrprojreqmain'[Request Status] <> "Cancelled"
			)
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 99389a19-436e-43cb-8fce-563ce98c2530

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Last Refreshed' = ```
			
			NOW()
			
			```
		formatString: General Date
		lineageTag: 5c68d1ff-4f9f-4c10-989d-f2b936f74d87

	measure 'Pipeline Est TPC' = ```
			
			CALCULATE (
			    SUM ( PROD_cmrprojreqmain[Estimated TPC (Cost Factored)] ),
			    PROD_cmrprojreqmain[Request Status] <> "Approved", PROD_cmrprojreqmain[Request Status] <> "Cancelled"
			)
			
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 14d33268-e235-4fbf-9d11-9a989028f1ed

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Pipeline Projects' = ```
			
			CALCULATE (
			    COUNTROWS ( PROD_cmrprojreqmain ),
			    PROD_cmrprojreqmain[Request Status] <> "Approved",
			    PROD_cmrprojreqmain[Request Status] <> "Cancelled"
			)
			
			```
		formatString: 0
		lineageTag: fbaad9cc-6a2c-41f3-a34a-0c9257cbf818

	measure 'Approved Projects' = ```
			
			CALCULATE (
			    COUNTROWS ( PROD_cmrprojreqmain ),
			    PROD_cmrprojreqmain[Request Status] = "Approved"
			)
			
			```
		formatString: 0
		lineageTag: a1a53329-1e06-484d-b77b-6bd8aafcf54d

	measure 'Total Project Value' = ```
			
			SUMX(
			    PROD_cmrprojreqmain,
			    IF(
			        ISBLANK(PROD_cmrprojreqmain[par requested tpc]) || PROD_cmrprojreqmain[par requested tpc] = 0,
			        PROD_cmrprojreqmain[Estimated TPC (Cost Factored)],
			        PROD_cmrprojreqmain[par requested tpc]
			    )
			)
			
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 07aac294-8063-4573-b6b9-3209bf245daa

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Total Project Value (Filtered)' = ```
			
			CALCULATE (
			    SUMX (
			        PROD_cmrprojreqmain,
			        IF (
			            ISBLANK ( PROD_cmrprojreqmain[par requested tpc] ) || PROD_cmrprojreqmain[par requested tpc] = 0,
			            PROD_cmrprojreqmain[Estimated TPC (Cost Factored)],
			            PROD_cmrprojreqmain[par requested tpc]
			        )
			    ),
			    PROD_cmrprojreqmain[Request Status] <> "Cancelled"
			)
			
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: e36ada3f-78d0-4c43-8189-737a68f6d926

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Project Count (Aligned)' = ```
			
			CALCULATE (
			    COUNTROWS ( PROD_cmrprojreqmain ),
			    FILTER (
			        PROD_cmrprojreqmain,
			        PROD_cmrprojreqmain[Request Status] <> "Cancelled"
			    )
			)
			
			```
		formatString: 0
		lineageTag: 3fd7c0af-1340-484b-8a55-82146d0dafc1

	measure 'BPF Status' = ```
			
			VAR CurrentRequestID = SELECTEDVALUE(PROD_cmrprojreqmain[Request ID])
			RETURN
			    CALCULATE(
			        MAX(PROD_cmrrequestprocess[Active Stage]),
			        FILTER(
			            PROD_cmrrequestprocess,
			            PROD_cmrrequestprocess[bpf_pmbcp_cmrprojreqmainid] = CurrentRequestID
			        )
			    )
			
			```
		lineageTag: be6838a6-d9f9-4176-89f3-663211f425bf

	measure 'True Request Status'
		lineageTag: d60cdfc8-60ab-4ac7-8447-09221c0e5e49

	column 'CMR Project Request Main'
		dataType: string
		isNullable: false
		sourceProviderType: nchar
		lineageTag: bff0c46e-65d9-4b12-b780-7d498a37ef42
		summarizeBy: none
		sourceColumn: pmbcp_cmrprojreqmainid

		annotation SummarizationSetBy = Automatic

	column 'Created On'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: d50f10ad-4b84-4d2a-a332-db7ce741a4fb
		summarizeBy: none
		sourceColumn: createdon

		variation Variation
			isDefault
			relationship: 4918b8a3-cbd3-4c55-bb6e-4ef648d3e79e
			defaultHierarchy: LocalDateTable_1fcdb57c-af0a-4f8d-a0ee-c21e287304b0.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Created By'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: 35f1cda3-bc4e-4e44-b675-bec7b88f8bca
		summarizeBy: none
		sourceColumn: createdbyname

		annotation SummarizationSetBy = Automatic

	column statuscodename
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 77030289-86d3-4961-b68e-0e47e8c7844d
		summarizeBy: none
		sourceColumn: statuscodename

		annotation SummarizationSetBy = Automatic

	column 'Request ID'
		dataType: string
		sourceProviderType: nvarchar(850)
		lineageTag: cb39a309-9a11-422c-9a5c-739c428470e1
		summarizeBy: none
		sourceColumn: pmbcp_reqid

		annotation SummarizationSetBy = Automatic

	column 'Asset Info'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: d87a30df-19df-4638-88ab-46daa89d04f1
		summarizeBy: none
		sourceColumn: pmbcp_assetinfo

		annotation SummarizationSetBy = Automatic

	column 'Budget Available'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		sourceProviderType: money
		lineageTag: 1169c6ad-215d-49cf-9747-199a51195ae5
		summarizeBy: none
		sourceColumn: pmbcp_budgetavail

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Budget Available Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 1b12daac-ab0e-4e3f-bc8f-004e0d374bca
		summarizeBy: none
		sourceColumn: pmbcp_budgetdate

		variation Variation
			isDefault
			relationship: 423074c4-cc38-4e7a-844d-3b2c003e9a1b
			defaultHierarchy: LocalDateTable_46db7fb3-7686-468f-abcf-08b7d71f9eed.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Cancel Request'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 8177d368-557f-4e53-9846-f0e5a041329c
		summarizeBy: none
		sourceColumn: pmbcp_cancelname

		annotation SummarizationSetBy = Automatic

	column 'Cancel Requestor Email'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: 5ea59d77-e6ea-4d11-a5c5-47e06cc4c400
		summarizeBy: none
		sourceColumn: pmbcp_cancelemail

		annotation SummarizationSetBy = Automatic

	column 'Cancelled Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 21eb4526-896d-4b4d-a543-679a4796ffa8
		summarizeBy: none
		sourceColumn: pmbcp_cancelleddate

		variation Variation
			isDefault
			relationship: 7a058c3b-0493-4065-b0fd-d541881caf86
			defaultHierarchy: LocalDateTable_773ed036-2996-4d3b-bb6e-41568a86c79a.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Cancelled Reason'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: d64c66a1-a18b-44b4-84ca-35230e718dd5
		summarizeBy: none
		sourceColumn: pmbcp_cancelreason

		annotation SummarizationSetBy = Automatic

	column 'Request Complete'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 4b32492b-02e5-4a7f-8eb9-25974477fb29
		summarizeBy: none
		sourceColumn: pmbcp_completename

		annotation SummarizationSetBy = Automatic

	column 'Complete Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 32981274-caa2-4873-8348-9d43ebcfe672
		summarizeBy: none
		sourceColumn: pmbcp_completedate

		variation Variation
			isDefault
			relationship: ea5e9aba-f330-490f-ba81-7aaa83bb2d9e
			defaultHierarchy: LocalDateTable_d0cae90a-48ca-47c1-9c0e-b2cdf5cdbdef.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Cashflow Current Year Amount'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		sourceProviderType: money
		lineageTag: 274ab25d-2fd4-41ca-bf8e-4b0632245ffc
		summarizeBy: sum
		sourceColumn: pmbcp_cyamount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Director Comments'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 769343e9-b884-4bb0-8e04-991f3b9ba8d1
		summarizeBy: none
		sourceColumn: pmbcp_dircomments

		annotation SummarizationSetBy = Automatic

	column 'Director Decision Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 62a39bfc-5179-4ddd-8c8f-1ef66d3fbe49
		summarizeBy: none
		sourceColumn: pmbcp_dirdecdate

		variation Variation
			isDefault
			relationship: 0b4447aa-e466-4f4f-aae3-db4942f044f1
			defaultHierarchy: LocalDateTable_fb1df0b5-e05e-44d9-8ff8-ae2e77abfa75.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Director Decision Email'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: c62dd3d4-b276-4293-a507-e8e463028713
		summarizeBy: none
		sourceColumn: pmbcp_dirdecemail

		annotation SummarizationSetBy = Automatic

	column 'Director Decision'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 41af7790-5c21-45bd-84ad-07b28fadafba
		summarizeBy: none
		sourceColumn: pmbcp_dirdecisionname

		annotation SummarizationSetBy = Automatic

	column 'Executive Director Decision'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 7e552506-5ec2-4159-a21d-c138d9a06b48
		summarizeBy: none
		sourceColumn: pmbcp_eddecisionname

		annotation SummarizationSetBy = Automatic

	column 'ED Decision Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 71cdb580-ffea-4201-b8eb-d6285623e65c
		summarizeBy: none
		sourceColumn: pmbcp_eddecisiondate

		variation Variation
			isDefault
			relationship: f18603f3-310c-4de8-a5c2-eb25b9f74e7f
			defaultHierarchy: LocalDateTable_28b2dbe4-bbd8-4b88-b4e9-62e5e15df71b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Sent to EDO'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 5d79e8fa-d7a3-4639-b35c-dd0f4c560383
		summarizeBy: none
		sourceColumn: pmbcp_edsent

		variation Variation
			isDefault
			relationship: 6afaa81e-893e-45e6-9668-c1b11e369df5
			defaultHierarchy: LocalDateTable_399c2dba-809e-4634-a02f-facb0ce696fa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Executive Review - Sent to PMPI Director'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 84bd9126-18ca-4de8-9b9b-d84146110b66
		summarizeBy: none
		sourceColumn: pmbcp_ersentpmpidir

		variation Variation
			isDefault
			relationship: 7300f459-ce73-4dae-818b-7975386b0c0b
			defaultHierarchy: LocalDateTable_91d5f470-7611-4aab-a135-3581fb4151dd.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Executive Review - Sent to PD Director'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: efc9be8c-50d2-4ddf-ab28-6d91312b6969
		summarizeBy: none
		sourceColumn: pmbcp_ersenttopd

		variation Variation
			isDefault
			relationship: 0bfdd12e-78f0-4ace-a708-9a72b92045c9
			defaultHierarchy: LocalDateTable_961a6a15-bf5b-436e-a6ca-c9a824f480bb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Estimated TPC (Cost Factored)'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		sourceProviderType: money
		lineageTag: e9667551-7cd6-4865-8ecd-597d47f5b619
		summarizeBy: sum
		sourceColumn: pmbcp_esttpc

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Executive Review Start Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 6ee78398-f59c-410f-b0af-ca6c8eabae33
		summarizeBy: none
		sourceColumn: pmbcp_execreviewstartdate

		variation Variation
			isDefault
			relationship: 145145e5-4081-48e4-a3b0-8017bd4806a8
			defaultHierarchy: LocalDateTable_a651941a-41ba-4556-aaa7-ef1bfc14e8cf.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Facilities Finalization'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: e9dadadd-5fb4-4a50-9f25-d4c7a947d549
		summarizeBy: none
		sourceColumn: pmbcp_facfinalname

		annotation SummarizationSetBy = Automatic

	column 'Facilities Finalization Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: a30b72d0-51a0-4e0a-af5e-fe91fdd0659e
		summarizeBy: none
		sourceColumn: pmbcp_facfinaldate

		variation Variation
			isDefault
			relationship: 979e4387-fa46-4d7f-9d39-0b07cce0b6ea
			defaultHierarchy: LocalDateTable_b4475e3f-1644-460a-8ca0-02559bba9902.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Finance Response Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 62bd3539-4294-4b31-afb7-cc1d352dafc0
		summarizeBy: none
		sourceColumn: pmbcp_finrespdate

		variation Variation
			isDefault
			relationship: 3ae6db53-37a6-4d69-947b-4b78bc8a453b
			defaultHierarchy: LocalDateTable_f4e8ea86-4652-4b3e-8ea9-7cc77f620c44.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Sent to Finance Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b668162c-8c39-4861-babf-8ac6570fadb7
		summarizeBy: none
		sourceColumn: pmbcp_finsentdate

		variation Variation
			isDefault
			relationship: 2a7b719f-3b4a-42ab-aab8-c59a1ea51059
			defaultHierarchy: LocalDateTable_9ef17384-bd1a-40f5-aef3-92765076c24e.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'FM Initial Decision Comments'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 1048c1d4-0229-4d10-b049-d7a034cd6501
		summarizeBy: none
		sourceColumn: pmbcp_fmcomments

		annotation SummarizationSetBy = Automatic

	column 'FM Initial Decision Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 378d7df2-2158-4b0a-82a9-427e8a509c5b
		summarizeBy: none
		sourceColumn: pmbcp_fmdecdate

		variation Variation
			isDefault
			relationship: dc83d143-12ed-4146-8d25-89006bc21b52
			defaultHierarchy: LocalDateTable_2fac0327-4e54-47a7-97fe-0fd2c4204f54.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'FM Decision Email'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: a5cb203b-678a-4f16-abac-5b987879c6de
		summarizeBy: none
		sourceColumn: pmbcp_fmdecemail

		annotation SummarizationSetBy = Automatic

	column 'FM Initial Decision'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 6c802038-9226-4d0d-a50b-ce924ac6e638
		summarizeBy: none
		sourceColumn: pmbcp_fmdecisionname

		annotation SummarizationSetBy = Automatic

	column 'Funding Classification'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 54fa94ec-b250-4274-8e25-116d3af15833
		summarizeBy: none
		sourceColumn: pmbcp_fundclassname

		annotation SummarizationSetBy = Automatic

	column 'Cashflow Future Year Amount'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		sourceProviderType: money
		lineageTag: 8426c850-cff5-4bd8-a209-9898a56c58b4
		summarizeBy: sum
		sourceColumn: pmbcp_fyamount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column Hazmat
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 69b2432b-7e18-4a0f-b53f-619bfeeafda9
		summarizeBy: none
		sourceColumn: pmbcp_hazmatname

		annotation SummarizationSetBy = Automatic

	column 'Hazmat Comments'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 7c004470-d4c2-4955-b6b2-bd175373d284
		summarizeBy: none
		sourceColumn: pmbcp_hazmatcomments

		annotation SummarizationSetBy = Automatic

	column 'Hazmat Plan'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 95006500-1601-480a-bff6-96585dc816c2
		summarizeBy: none
		sourceColumn: pmbcp_hazmatplanname

		annotation SummarizationSetBy = Automatic

	column 'Highest Scoring REQ ID'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: 570e9513-f231-4f88-a645-da8b0dd99f46
		summarizeBy: none
		sourceColumn: pmbcp_highscorereq

		annotation SummarizationSetBy = Automatic

	column 'Initiator Email'
		dataType: string
		sourceProviderType: nvarchar(400)
		lineageTag: 459ff171-9180-4871-9b66-28d11796fc35
		summarizeBy: none
		sourceColumn: pmbcp_initiatoremail

		annotation SummarizationSetBy = Automatic

	column 'Occupant Impact'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 6b63a89f-8e43-4c76-a94a-64cb4e733742
		summarizeBy: none
		sourceColumn: pmbcp_occupantimpactname

		annotation SummarizationSetBy = Automatic

	column 'PD PAR Received Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: d2e75633-3dec-4c18-824c-aad74e10bcc1
		summarizeBy: none
		sourceColumn: pmbcp_pardate

		variation Variation
			isDefault
			relationship: f54bcad5-07e6-4299-86cd-6c28a5127d58
			defaultHierarchy: LocalDateTable_318d9f43-9fca-43ef-af4c-f1a29f189627.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'PAR Requested TPC'
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		sourceProviderType: money
		lineageTag: 67a29465-31a0-449b-82d5-73b38b99032d
		summarizeBy: sum
		sourceColumn: pmbcp_parreq

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Project Controls Notes'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 9b4d38c0-11e3-43ca-a207-b63f5e5cfbb9
		summarizeBy: none
		sourceColumn: pmbcp_pcnotes

		annotation SummarizationSetBy = Automatic

	column 'PD Director Complete Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: ea4eff8d-8aae-4622-9493-d304bfbc2d4c
		summarizeBy: none
		sourceColumn: pmbcp_pddircompdate

		variation Variation
			isDefault
			relationship: 6618a791-e35f-42a9-b6a3-114655072906
			defaultHierarchy: LocalDateTable_373b6582-c27a-4597-bbe3-b94e10f57b7b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'PD PAR Received'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: a18d46c2-9be4-4470-8796-97cceacf2b18
		summarizeBy: none
		sourceColumn: pmbcp_pdparrecdname

		annotation SummarizationSetBy = Automatic

	column 'PD Project Title'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: e9b36fd7-cd85-4224-9baa-a2cf53a813d0
		summarizeBy: none
		sourceColumn: pmbcp_pdprojecttitle

		annotation SummarizationSetBy = Automatic

	column 'Project Delivery Required'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 853c9e9a-4edf-4823-b24a-80810bd1c129
		summarizeBy: none
		sourceColumn: pmbcp_pdrequiredname

		annotation SummarizationSetBy = Automatic

	column 'Planned Status'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: 92e0b42c-9253-4cfb-9e04-61c25e6d03ca
		summarizeBy: none
		sourceColumn: pmbcp_plannedstatus

		annotation SummarizationSetBy = Automatic

	column 'PMPI Director Complete Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 04e355e8-9094-4292-95fc-7d75275750da
		summarizeBy: none
		sourceColumn: pmbcp_pmpidircompdateer

		variation Variation
			isDefault
			relationship: 6bace3fa-5f32-45a1-826a-8aa3c6ac26fe
			defaultHierarchy: LocalDateTable_ca6ae3bd-a6ec-487c-b275-152789ded806.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Project Priority Score'
		dataType: string
		sourceProviderType: nvarchar(1000)
		lineageTag: 19a4d66b-20ff-4a6a-b048-2cc5ab58476b
		summarizeBy: none
		sourceColumn: pmbcp_priorityscore

		annotation SummarizationSetBy = Automatic

	column 'Project Lead'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: fd9bd852-9941-4269-86f5-532d23f1e382
		summarizeBy: none
		sourceColumn: pmbcp_projectleadname

		annotation SummarizationSetBy = Automatic

	column 'Project Work Hours'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 10bfcb32-409b-4888-bc72-7307f046c4e3
		summarizeBy: none
		sourceColumn: pmbcp_projectworkhoursname

		annotation SummarizationSetBy = Automatic

	column 'Project Server Setup Complete Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: b46fcbd7-bc26-4beb-8607-2bf73b293a50
		summarizeBy: none
		sourceColumn: pmbcp_projservsetupdate

		variation Variation
			isDefault
			relationship: 67147342-210b-41dc-aa0e-c44dbe06b1b2
			defaultHierarchy: LocalDateTable_2775e3df-eb72-4f2f-bfb3-abc7f29d95df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'RAP ID'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: e8f0a59c-2245-46fb-807d-69f4deee117f
		summarizeBy: none
		sourceColumn: pmbcp_rapid

		annotation SummarizationSetBy = Automatic

	column 'Related Comments'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 4c5cd5db-740d-4ed8-8d12-6c44121a9e6e
		summarizeBy: none
		sourceColumn: pmbcp_relatedcomments

		annotation SummarizationSetBy = Automatic

	column pmbcp_relatedproject
		dataType: string
		sourceProviderType: nchar
		lineageTag: 7113d652-1d92-4ce7-87f5-9b7cf2841797
		summarizeBy: none
		sourceColumn: pmbcp_relatedproject

		annotation SummarizationSetBy = Automatic

	column 'REQ ID(s)'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: ca0438ca-cce9-4a19-8026-3c62fb6ae03b
		summarizeBy: none
		sourceColumn: pmbcp_reqids

		annotation SummarizationSetBy = Automatic

	column 'REQ Name(s)'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 51265ecb-5c8d-48df-810f-214ba024d6a7
		summarizeBy: none
		sourceColumn: pmbcp_reqnames

		annotation SummarizationSetBy = Automatic

	column 'Request Type'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 5436aa6b-65fa-44ac-b6ea-f241813fe83f
		summarizeBy: none
		sourceColumn: pmbcp_reqtypename

		annotation SummarizationSetBy = Automatic

	column 'Sent to Project Delivery'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: ce8ea891-a898-457b-ae64-8e967ab3d53d
		summarizeBy: none
		sourceColumn: pmbcp_sentpd

		variation Variation
			isDefault
			relationship: b4772a73-6d29-45af-8cfc-b593d75e00f9
			defaultHierarchy: LocalDateTable_38ef3e40-522c-46a9-86b2-8f598cd1bd04.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Starting Fiscal Year'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: 2944fe36-9492-4426-910f-70849708e4c2
		summarizeBy: none
		sourceColumn: pmbcp_startingfiscalyear

		annotation SummarizationSetBy = Automatic

	column 'Request Status'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 333d2202-7618-413e-a9c4-bd93d4aa0a65
		summarizeBy: none
		sourceColumn: pmbcp_statusname

		annotation SummarizationSetBy = Automatic

	column 'Tech Review BDS Manager Complete'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: d125c329-6cff-4c2c-baec-b03e889cedfa
		summarizeBy: none
		sourceColumn: pmbcp_techrevbdsmgrname

		annotation SummarizationSetBy = Automatic

	column 'Tech Review BDS Manager Complete Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 0f0768e7-2090-456d-9b02-64ea199942bb
		summarizeBy: none
		sourceColumn: pmbcp_techrevbdsmgrdate

		variation Variation
			isDefault
			relationship: f3648431-915c-452f-819e-b0feacbf1665
			defaultHierarchy: LocalDateTable_c6f3c19c-38af-4e29-b5b5-02411be9b1ac.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Tech Review Draft Complete'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 6b808115-cb01-4ff9-9c0d-463d04cd9e28
		summarizeBy: none
		sourceColumn: pmbcp_techrevdraft

		variation Variation
			isDefault
			relationship: fecdd3c3-2b42-4e02-b297-4cd8d0428b1d
			defaultHierarchy: LocalDateTable_50edb8a3-7641-4496-8882-de4cd771c1a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Tech Review Notes'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: e0bc05bc-ea9e-4947-9f58-3aef40264d09
		summarizeBy: none
		sourceColumn: pmbcp_techrevnotes

		annotation SummarizationSetBy = Automatic

	column 'Tech Review PMPI Director Complete'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 4bb1bb71-edd9-476a-84b0-b06464d7c347
		summarizeBy: none
		sourceColumn: pmbcp_techrevpmpidirname

		annotation SummarizationSetBy = Automatic

	column 'Tech Review PMPI Director Complete Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 07e91a03-8fd9-4ab0-872b-94539326fdcb
		summarizeBy: none
		sourceColumn: pmbcp_techrevpmpidirdate

		variation Variation
			isDefault
			relationship: cb22edda-9bb9-4ade-9fbe-884ee8460254
			defaultHierarchy: LocalDateTable_0d4b2fe4-b6b5-4579-ba2d-dbe004509120.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Response to Tech Review Report'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 27588ecb-8580-4f96-8ead-b3ee0fc9c940
		summarizeBy: none
		sourceColumn: pmbcp_techrevresp

		annotation SummarizationSetBy = Automatic

	column 'Technical Review Status'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 8a35e1f7-bd1d-4901-8b9f-4ae821cddb32
		summarizeBy: none
		sourceColumn: pmbcp_techrevstatusname

		annotation SummarizationSetBy = Automatic

	column 'Tech Review Waived Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: ac4f7104-de38-40e8-93da-a135dfc3010a
		summarizeBy: none
		sourceColumn: pmbcp_techrevwaiveddate

		variation Variation
			isDefault
			relationship: 1c2d8f91-732b-4bbf-99ca-9a65e31b936e
			defaultHierarchy: LocalDateTable_b7d6dd3a-df8f-451c-9178-2af3ea2322db.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Tech Review Waived Reason'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: 5300b36e-8ccc-436e-b9cf-30d0670de4e9
		summarizeBy: none
		sourceColumn: pmbcp_techrevwaivedreason

		annotation SummarizationSetBy = Automatic

	column Title
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: 7bceb701-8785-4036-b203-523a995d8fab
		summarizeBy: none
		sourceColumn: pmbcp_title

		annotation SummarizationSetBy = Automatic

	column 'Urgent Request'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: c9cb114a-89b3-43a4-95a8-d63ae55e49fc
		summarizeBy: none
		sourceColumn: pmbcp_urgentname

		annotation SummarizationSetBy = Automatic

	column 'Urgent Justification'
		dataType: string
		sourceProviderType: nvarchar(4000)
		lineageTag: bf5a8baa-f8f1-44f3-8588-dcc748e894a4
		summarizeBy: none
		sourceColumn: pmbcp_urgentjust

		annotation SummarizationSetBy = Automatic

	column 'WBS Element'
		dataType: string
		sourceProviderType: nvarchar(100)
		lineageTag: 20ebe682-4795-459c-92ae-8dbcf401eb71
		summarizeBy: none
		sourceColumn: pmbcp_wbselement

		annotation SummarizationSetBy = Automatic

	column 'WBS Sent Date'
		dataType: dateTime
		formatString: General Date
		sourceProviderType: datetime2
		lineageTag: 18861cbc-5a09-4277-9183-264229c7098e
		summarizeBy: none
		sourceColumn: pmbcp_wbssentdate

		variation Variation
			isDefault
			relationship: 6425f7c9-f042-4471-b840-90b069aa2280
			defaultHierarchy: LocalDateTable_68afeacc-f701-4af9-9246-60ac087f4d90.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column 'Work Status'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 8bfd454e-0758-443d-9b4d-30230d52b6d1
		summarizeBy: none
		sourceColumn: pmbcp_workstatusname

		annotation SummarizationSetBy = Automatic

	column 'Director Responsible'
		dataType: string
		sourceProviderType: nvarchar(256)
		lineageTag: b2ed31fc-512d-4bff-8bf2-e397a66879a6
		summarizeBy: none
		sourceColumn: pmbcp_dirrespname

		annotation SummarizationSetBy = Automatic

	column pmbcp_dirrespyominame
		dataType: string
		sourceProviderType: nvarchar(256)
		lineageTag: c2569f28-2c93-486c-80b1-556768c1d76e
		summarizeBy: none
		sourceColumn: pmbcp_dirrespyominame

		annotation SummarizationSetBy = Automatic

	column 'Facilities Manager Responsible'
		dataType: string
		sourceProviderType: nvarchar(256)
		lineageTag: 5a9bab83-40a0-45d9-9bec-4b8fbc16f152
		summarizeBy: none
		sourceColumn: pmbcp_fmrespname

		annotation SummarizationSetBy = Automatic

	column pmbcp_fmrespyominame
		dataType: string
		sourceProviderType: nvarchar(256)
		lineageTag: 1f617a9b-7cbf-4682-a805-49904ba5c93b
		summarizeBy: none
		sourceColumn: pmbcp_fmrespyominame

		annotation SummarizationSetBy = Automatic

	column 'Project Manager'
		dataType: string
		sourceProviderType: nvarchar(256)
		lineageTag: 5075d44d-26a0-4eb0-a3f1-31e8da0b3f2b
		summarizeBy: none
		sourceColumn: pmbcp_pmname

		annotation SummarizationSetBy = Automatic

	column 'Project Lookup'
		dataType: string
		sourceProviderType: nvarchar(850)
		lineageTag: 40b0c830-012a-4bc5-b65f-698c3c933cc5
		summarizeBy: none
		sourceColumn: pmbcp_projectlookupname

		annotation SummarizationSetBy = Automatic

	column 'Related Project Lookup'
		dataType: string
		sourceProviderType: nvarchar(850)
		lineageTag: 8981b561-af29-46cf-aff8-951517e99f18
		summarizeBy: none
		sourceColumn: pmbcp_relatedprojectname

		annotation SummarizationSetBy = Automatic

	column 'Tech Review Action Comments'
		dataType: string
		sourceProviderType: nvarchar(max)
		lineageTag: 58ba2ce0-329b-4cc7-a81c-a257ce15f3e8
		summarizeBy: none
		sourceColumn: pmbcp_techrevactioncom

		annotation SummarizationSetBy = Automatic

	column 'Cashflow Percent'
		dataType: string
		sourceProviderType: nvarchar(75)
		lineageTag: 44ffa66a-e89b-4c43-9935-1e9a6819b960
		summarizeBy: none
		sourceColumn: pmbcp_cashflowpercentname

		annotation SummarizationSetBy = Automatic

	column 'Actual Request Status' =
			
			LOOKUPVALUE(
			    PROD_cmrrequestprocess[Active Stage],
			    PROD_cmrrequestprocess[Pmbcp_Cmrprojreqmain],
			    PROD_cmrprojreqmain[Request ID]
			)
		lineageTag: 7394c7eb-8e94-4d95-ba8c-713e5bd9cc15
		summarizeBy: none

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	partition PROD_cmrprojreqmain = m
		mode: import
		queryGroup: Reporting_Tables
		source = ```
				let
				    Source = CommonDataService.Database("org509f7c88.crm3.dynamics.com"),
				    dbo_pmbcp_cmrprojreqmain = Source{[Schema = "dbo", Item = "pmbcp_cmrprojreqmain"]}[Data],
				    #"Removed Columns" = Table.RemoveColumns(
				        dbo_pmbcp_cmrprojreqmain,
				        {
				            "createdonbehalfby",
				            "modifiedonbehalfby",
				            "createdbyyominame",
				            "createdonbehalfbyname",
				            "createdonbehalfbyyominame",
				            "modifiedbyname",
				            "modifiedbyyominame",
				            "modifiedonbehalfbyname",
				            "modifiedonbehalfbyyominame",
				            "ownerid",
				            "owneridname",
				            "owneridyominame",
				            "owningbusinessunit",
				            "owninguser",
				            "owningteam",
				            "owningbusinessunitname",
				            "statecode",
				            "statecodename",
				            "statuscode",
				            "importsequencenumber",
				            "overriddencreatedon",
				            "timezoneruleversionnumber",
				            "utcconversiontimezonecode",
				            "transactioncurrencyid",
				            "transactioncurrencyidname",
				            "exchangerate",
				            "pmbcp_budgetavail_base",
				            "pmbcp_changeurgency",
				            "pmbcp_changeurgencyname",
				            "pmbcp_changeurgreason",
				            "pmbcp_cyamount_base",
				            "pmbcp_esttpc_base",
				            "pmbcp_facfinal",
				            "pmbcp_dirdecision",
				            "createdby",
				            "modifiedon",
				            "modifiedby",
				            "pmbcp_cancel",
				            "pmbcp_complete",
				            "pmbcp_dirresp",
				            "pmbcp_eddecision",
				            "pmbcp_finnotes",
				            "pmbcp_fundclass",
				            "pmbcp_fundingsourcecomments",
				            "pmbcp_fyamount_base",
				            "pmbcp_hazmat",
				            "pmbcp_hazmatplan",
				            "pmbcp_occupantimpact",
				            "pmbcp_pdparrecd",
				            "pmbcp_pdrequired",
				            "pmbcp_pm",
				            "pmbcp_projectlead",
				            "pmbcp_projectlookup",
				            "pmbcp_projectworkhours",
				            "pmbcp_recordlink",
				            "pmbcp_reqnotes",
				            "pmbcp_reqtype",
				            "pmbcp_resenddecisionreason",
				            "pmbcp_resenddecisiontask",
				            "pmbcp_resenddecisiontaskname",
				            "pmbcp_status",
				            "pmbcp_supdocfolder",
				            "pmbcp_techrevbdsmgr",
				            "pmbcp_techrevene",
				            "pmbcp_techrevfileid",
				            "pmbcp_techrevlink",
				            "pmbcp_techrevohs",
				            "pmbcp_techrevohsname",
				            "pmbcp_techrevom",
				            "pmbcp_techrevomname",
				            "pmbcp_techrevpmpidir",
				            "pmbcp_techrevsec",
				            "pmbcp_techrevsecname",
				            "pmbcp_techrevstatus",
				            "pmbcp_urgent",
				            "pmbcp_vfareports",
				            "pmbcp_vfareportsname",
				            "pmbcp_workstatus",
				            "processid",
				            "stageid",
				            "traversedpath",
				            "pmbcp_pmyominame",
				            "pmbcp_cashflowpercent",
				            "asyncoperation",
				            "businessunit",
				            "pmbcp_cmrrequestprocess",
				            "pmbcp_projectsummarydata(pmbcp_projectlookup)",
				            "pmbcp_projectsummarydata(pmbcp_relatedproject)",
				            "pmbcp_vfadatavalidation",
				            "processsession",
				            "processstage",
				            "systemuser(createdby)",
				            "systemuser(createdonbehalfby)",
				            "systemuser(modifiedby)",
				            "systemuser(modifiedonbehalfby)",
				            "systemuser(owninguser)",
				            "systemuser(pmbcp_dirresp)",
				            //"systemuser(pmbcp_fmresp)",
				            "systemuser(pmbcp_pm)",
				            "team",
				            "transactioncurrency",
				            "pmbcp_fmdecision",
				            "pmbcp_fmresp",
				            "pmbcp_parlink",
				            "pmbcp_parreq_base",
				            "pmbcp_spofolderid",
				            "pmbcp_techrevenename"
				        }
				    ),
				    #"Reordered Columns" = Table.ReorderColumns(
				        #"Removed Columns",
				        {
				            //aggregate report columns
				            "pmbcp_reqid",
				            "pmbcp_rapid",
				            "pmbcp_projectlookupname",
				            "pmbcp_urgentname",
				            "pmbcp_projectleadname",
				            "pmbcp_techrevstatusname",
				            "pmbcp_assetinfo",
				            "pmbcp_dirdecisionname",
				            "pmbcp_fundclassname",
				            "pmbcp_esttpc",
				            "pmbcp_parreq",
				            "pmbcp_budgetavail",
				            "pmbcp_budgetdate",
				            "pmbcp_cyamount",
				            "pmbcp_eddecisionname",
				            //reportable date columns
				            "createdon",
				            "systemuser(pmbcp_fmresp)",
				            "pmbcp_fmdecdate",
				            "pmbcp_dirdecdate",
				            "pmbcp_facfinaldate",
				            "pmbcp_finrespdate",         
				            "pmbcp_eddecisiondate",
				            "pmbcp_edsent",
				            "pmbcp_ersentpmpidir",
				            "pmbcp_ersenttopd",
				            "pmbcp_execreviewstartdate",
				            "pmbcp_facfinalname",
				            "pmbcp_finsentdate",
				            "pmbcp_fmcomments",
				            "pmbcp_dirdecemail",
				            "pmbcp_fmdecemail",
				            "pmbcp_fmdecisionname",
				            "pmbcp_fyamount",
				            "pmbcp_hazmatname",
				            "pmbcp_hazmatcomments",
				            "pmbcp_hazmatplanname",
				            "pmbcp_highscorereq",
				            "pmbcp_initiatoremail",
				            "pmbcp_occupantimpactname",
				            "pmbcp_pardate",
				            "pmbcp_pcnotes",
				            "pmbcp_pddircompdate",
				            "pmbcp_pdparrecdname",
				            "pmbcp_pdprojecttitle",
				            "pmbcp_pdrequiredname",
				            "pmbcp_plannedstatus",
				            "pmbcp_pmpidircompdateer",
				            "pmbcp_priorityscore",
				            "pmbcp_projectworkhoursname",
				            "pmbcp_projservsetupdate",
				            "pmbcp_relatedcomments",
				            "pmbcp_relatedproject",
				            "pmbcp_reqids",
				            "pmbcp_reqnames",
				            "pmbcp_reqtypename",
				            "pmbcp_sentpd",
				            "pmbcp_startingfiscalyear",
				            "pmbcp_statusname",
				            "pmbcp_techrevbdsmgrname",
				            "pmbcp_techrevbdsmgrdate",
				            "pmbcp_techrevdraft",
				            "pmbcp_techrevnotes",
				            "pmbcp_techrevpmpidirname",
				            "pmbcp_techrevpmpidirdate",
				            "pmbcp_techrevresp",
				            "pmbcp_techrevwaiveddate",
				            "pmbcp_techrevwaivedreason",
				            "pmbcp_title",
				            "pmbcp_urgentjust",
				            "pmbcp_wbselement",
				            "pmbcp_wbssentdate",
				            "pmbcp_workstatusname",
				            "pmbcp_dirrespname",
				            "pmbcp_dirrespyominame",
				            "pmbcp_fmrespname",
				            "pmbcp_fmrespyominame",
				            "pmbcp_pmname",
				            "pmbcp_relatedprojectname",
				            "pmbcp_techrevactioncom",
				            "pmbcp_cashflowpercentname",
				            "pmbcp_cmrprojreqmainid",
				            "pmbcp_dircomments",
				            "createdbyname",
				            "statuscodename",
				            "pmbcp_completename",
				            "pmbcp_completedate",
				            "pmbcp_cancelname",
				            "pmbcp_cancelreason",
				            "pmbcp_cancelleddate",
				            "pmbcp_cancelemail"
				        }
				    ),
				    #"Replaced Value" = Table.ReplaceValue(#"Reordered Columns",null,"Pending Director Decision",Replacer.ReplaceValue,{"pmbcp_dirdecisionname"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value",null,"Pending",Replacer.ReplaceValue,{"pmbcp_fundclassname"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1",null,"Pending Facilities Finalization",Replacer.ReplaceValue,{"pmbcp_facfinalname"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Replaced Value2",{"pmbcp_statusname", "pmbcp_reqid", "pmbcp_rapid", "pmbcp_projectlookupname", "pmbcp_urgentname", "pmbcp_projectleadname", "pmbcp_techrevstatusname", "pmbcp_assetinfo", "pmbcp_dirdecisionname", "pmbcp_fundclassname", "pmbcp_esttpc", "pmbcp_parreq", "pmbcp_budgetavail", "pmbcp_budgetdate", "pmbcp_cyamount", "pmbcp_eddecisionname", "createdon", "pmbcp_fmdecdate", "pmbcp_dirdecdate", "pmbcp_facfinaldate", "pmbcp_finrespdate", "pmbcp_eddecisiondate", "pmbcp_edsent", "pmbcp_ersentpmpidir", "pmbcp_ersenttopd", "pmbcp_execreviewstartdate", "pmbcp_facfinalname", "pmbcp_finsentdate", "pmbcp_fmcomments", "pmbcp_dirdecemail", "pmbcp_fmdecemail", "pmbcp_fmdecisionname", "pmbcp_fyamount", "pmbcp_hazmatname", "pmbcp_hazmatcomments", "pmbcp_hazmatplanname", "pmbcp_highscorereq", "pmbcp_initiatoremail", "pmbcp_occupantimpactname", "pmbcp_pardate", "pmbcp_pcnotes", "pmbcp_pddircompdate", "pmbcp_pdparrecdname", "pmbcp_pdprojecttitle", "pmbcp_pdrequiredname", "pmbcp_plannedstatus", "pmbcp_pmpidircompdateer", "pmbcp_priorityscore", "pmbcp_projectworkhoursname", "pmbcp_projservsetupdate", "pmbcp_relatedcomments", "pmbcp_relatedproject", "pmbcp_reqids", "pmbcp_reqnames", "pmbcp_reqtypename", "pmbcp_sentpd", "pmbcp_startingfiscalyear", "pmbcp_techrevbdsmgrname", "pmbcp_techrevbdsmgrdate", "pmbcp_techrevdraft", "pmbcp_techrevnotes", "pmbcp_techrevpmpidirname", "pmbcp_techrevpmpidirdate", "pmbcp_techrevresp", "pmbcp_techrevwaiveddate", "pmbcp_techrevwaivedreason", "pmbcp_title", "pmbcp_urgentjust", "pmbcp_wbselement", "pmbcp_wbssentdate", "pmbcp_workstatusname", "pmbcp_dirrespname", "pmbcp_dirrespyominame", "pmbcp_fmrespname", "pmbcp_fmrespyominame", "pmbcp_pmname", "pmbcp_relatedprojectname", "pmbcp_techrevactioncom", "pmbcp_cashflowpercentname", "pmbcp_cmrprojreqmainid", "pmbcp_dircomments", "createdbyname", "statuscodename", "pmbcp_completename", "pmbcp_completedate", "pmbcp_cancelname", "pmbcp_cancelreason", "pmbcp_cancelleddate", "pmbcp_cancelemail"})
				in
				    #"Reordered Columns1"
				```

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

