table 'Capital Plan 2025-26'
	lineageTag: a963b353-913d-40ef-bbf3-838a3295817a

	measure ForecastAcum = ```
			
			CALCULATE(
			    SUM('Capital Plan 2025-26'[Forecast]),
			    FILTER(
			        ALLSELECTED('Capital Plan 2025-26'),'Capital Plan 2025-26'[Accum]<= MAX('Capital Plan 2025-26'[Accum])
			    
			    ))
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: d0f873ff-53e7-4e2f-addf-efc51d26d7f8

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure TargetAccum = ```
			
			CALCULATE(
			    SUM('Capital Plan 2025-26'[Target]),
			    FILTER(
			        ALLSELECTED('Capital Plan 2025-26'),'Capital Plan 2025-26'[Accum]< MAX('Capital Plan 2025-26'[Accum])
			    
			    ))
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 086fbe8c-7dc4-4e3f-a470-381ab34a741e

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure 'Target Increment' = ```
			
			VAR CurrentAccum = MAX('Capital Plan 2025-26'[Accum])
			VAR CurrentTarget = 
			    CALCULATE(
			        MAX('Capital Plan 2025-26'[Target]),
			        FILTER(
			            ALL('Capital Plan 2025-26'),
			            'Capital Plan 2025-26'[Accum] = CurrentAccum
			        )
			    )
			VAR PrevTarget = 
			    CALCULATE(
			        MAX('Capital Plan 2025-26'[Target]),
			        FILTER(
			            ALL('Capital Plan 2025-26'),
			            'Capital Plan 2025-26'[Accum] = CurrentAccum - 1
			        )
			    )
			RETURN
			    CurrentTarget - PrevTarget
			
			
			
			```
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 87f67fd5-9fe4-421c-96b7-d4a8fc46e5cc

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure '3-Year Budget Available' = [Target Increment]+[TargetAccum]-[ForecastAcum]
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: f9fadc1a-aa63-4d1a-9ce5-539ef3cb97da

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure '3-Year Budget Available + 20%' = [Target Increment]+[TargetAccum]+[Target+20]-[ForecastAcum]
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 1f10afdc-5583-4945-af46-7820fe6cff1c

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	measure Target+20 = ([TargetAccum]+[Target Increment])*0.2
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 7b3f8d9c-83b0-4f9e-97a4-ceeb3f24a15d

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Capital Project/Program by Name'
		dataType: string
		lineageTag: d2dbaf09-9480-4fd4-b2d2-1d4e8c356bc6
		summarizeBy: none
		sourceColumn: Capital Project/Program by Name

		annotation SummarizationSetBy = Automatic

	column 'Funding Classification'
		dataType: string
		lineageTag: b58d1643-7d41-40b6-90a8-526b29301081
		summarizeBy: none
		sourceColumn: Funding Classification

		annotation SummarizationSetBy = Automatic

	column 'Fiscal Year'
		dataType: string
		lineageTag: 44752215-75b8-404b-892b-4630906037cf
		summarizeBy: none
		sourceColumn: Fiscal Year
		sortByColumn: Accum

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column Forecast
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 3d55aa96-827c-425d-8663-3c3e55274580
		summarizeBy: sum
		sourceColumn: Forecast

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column Target
		dataType: decimal
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 919bad49-8794-4e7d-abec-e15cde4a3971
		summarizeBy: sum
		sourceColumn: Target

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column Accum
		dataType: dateTime
		formatString: Long Date
		lineageTag: 855b02b8-fa70-4345-abdc-a006efd960cf
		summarizeBy: none
		sourceColumn: Accum

		variation Variation
			isDefault
			relationship: 0658fbb8-222d-4853-834d-5ca55495b9a0
			defaultHierarchy: LocalDateTable_b4f83d40-2dec-495b-aeab-1241f4a38355.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Target+20 - Operating' = 'Capital Plan 2025-26'[Target]*0.2
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: b78657cd-61fb-4e30-933a-7cb16d4fcd68
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Unallocated Budget +20 OP' = 'Capital Plan 2025-26'[Target+20 - Operating]+'Capital Plan 2025-26'[Target]-'Capital Plan 2025-26'[Forecast]
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 0dfbec99-6189-403d-8773-a9bcdd779a5e
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Unallocated Budget - OP' = 'Capital Plan 2025-26'[Target]-'Capital Plan 2025-26'[Forecast]
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 34d64003-10a4-428c-96d4-ad804cb25b2a
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	column 'Target+20 Total' = 'Capital Plan 2025-26'[Target]*1.2
		formatString: \$#,0.###############;-\$#,0.###############;\$#,0.###############
		lineageTag: 0dc4d100-fff8-4bbb-a78f-05f36d066fe6
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"en-CA"}

	partition 'Capital Plan 2025-26' = m
		mode: import
		source = ```
				let
				    Source = Excel.Workbook(Web.Contents("https://abgov.sharepoint.com/sites/PWAD13-PMBPS/PMPI/Biweekly%20Report%202024-2025%20(Project%20Server)-%20In%20Progress%20(New%20Year).xlsx"), null, true),
				    #"Capital Plan 2025-26_Sheet" = Source{[Item="Capital Plan 2025-26",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Capital Plan 2025-26_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Column1", type text}, {"Column2", type text}, {"All $ values in $1,000s", type text}, {"Column4", type any}, {"Column5", type text}, {"Column6", type text}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}, {"Column13", type any}, {"Column14", type any}, {"Column15", type any}, {"Column16", type any}, {"Column17", type any}, {"Column18", type any}, {"Column19", type any}, {"Column20", type any}, {"Column21", type any}, {"Column22", type any}, {"Column23", type any}, {"Column24", type any}, {"Column25", type any}, {"Column26", type any}, {"Column27", type any}, {"Column28", type any}, {"Column29", type any}, {"Column30", type any}, {"Column31", type any}, {"Column32", type any}, {"Column33", type any}, {"Column34", type any}, {"Column35", type any}, {"Column36", type any}, {"Column37", type any}, {"Column38", type any}, {"Column39", type any}, {"Column40", type any}, {"Column41", type any}, {"Column42", type any}, {"Column43", type any}, {"Column44", type any}, {"Column45", type any}, {"Column46", type any}, {"Column47", type any}, {"Column48", type any}, {"Column49", type any}, {"Column50", type any}, {"Column51", type any}, {"Column52", type any}, {"Column53", type any}, {"Column54", type any}, {"Column55", type any}, {"Column56", type any}, {"Column57", type any}, {"Column58", type any}, {"Column59", type any}, {"Column60", type any}, {"Column61", type any}}),
				    #"Removed Top Rows" = Table.Skip(#"Changed Type",1),
				    #"Promoted Headers1" = Table.PromoteHeaders(#"Removed Top Rows", [PromoteAllScalars=true]),
				    #"Removed Columns" = Table.RemoveColumns(#"Promoted Headers1",{"Location", "Constituency", "Column4", "Project ID#(lf)(Bi-weekly)", "Project ID          (If It is not Program)", "Project Type", "Prior Year Actuals#(lf)(2023-24)", "Prior Year Actuals#(lf)(2024-25)", "# of Projects in 2025-26", "Total Project Cost (TPC)", "2025-26 Actuals", "Column27", "2025-26#(lf)Target_1", "2026-27#(lf)Target_2", "2027-28#(lf)Target_3", "2028-29#(lf)Target_4", "Column34", "2025-26#(lf)Target_7", "2026-27#(lf)Target_8", "2027-28#(lf)Target_9", "2028-29#(lf)Target_10", "Column41", "2025-26#(lf)Target_13", "2026-27#(lf)Target_14", "2027-28#(lf)Target_15", "2028-29#(lf)Target_16", "3-Year#(lf)Forecast % of Q3", "Column50", "2025-26#(lf)Target_20", "2026-27#(lf)Target_21", "2027-28#(lf)Target_22", "2028-29#(lf)Target_23", "3-Year#(lf)Forecast % of Q4", "Column59", "Column60", "Column61", "Forecast 2028-29", "3-Year#(lf)Forecast % of B2025", "2028-29#(lf)Target", "2029-30#(lf)Target", "3-Year#(lf) Total", "5-Year#(lf)Total", "3-Year#(lf)Forecast Total", "(B2025)#(lf)3-Year#(lf)Target", "5-Year#(lf)Total_6", "5-Year#(lf)Total_12", "3-Year#(lf)Forecast Total_18", "5-Year#(lf)Total_19", "2029-30#(lf)Target_24", "3-Year#(lf)Forecast Total_25", "5-Year#(lf)Total_26", "2029-30#(lf)Target_17", "2029-30#(lf)Target_11"}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Removed Columns",{{"Forecast 2025-26", Currency.Type}, {"Forecast 2026-27", Currency.Type}, {"Forecast 2027-28", Currency.Type}, {"2025-26#(lf)Target", Currency.Type}, {"2026-27#(lf)Target", Currency.Type}, {"2027-28#(lf)Target", Currency.Type}, {"2029-30#(lf)Target_5", Currency.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type1", each ([#"Capital Project/Program by Name"] = "Government-Owned Facilities - Capital Maintenance and Renewal (Capital Investment Vote portion only)" or [#"Capital Project/Program by Name"] = "Government-Owned Facilities - Capital Maintenance and Renewal (Operations Expense portion only)")),
				    #"Added Conditional Column" = Table.AddColumn(#"Filtered Rows", "Funding Classification", each if Text.Contains([#"Capital Project/Program by Name"], "(Capital Investment Vote") then "Capital Investment" else if Text.Contains([#"Capital Project/Program by Name"], "(Operations Expense") then "Operating" else null),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Conditional Column",{{"2025-26#(lf)Target", "2025-26 Target"}, {"2026-27#(lf)Target", "2026-27 Target"}, {"2027-28#(lf)Target", "2027-28 Target"}, {"Forecast 2027-28", "2027-28 Forecast"}, {"Forecast 2026-27", "2026-27 Forecast"}, {"Forecast 2025-26", "2025-26 Forecast"}, {"2029-30#(lf)Target_5", "2029-30 Target"}}),
				    #"Multiplied Column5" = Table.TransformColumns(#"Renamed Columns", {{"2025-26 Forecast", each _ * 1000, Currency.Type}}),
				    #"Multiplied Column6" = Table.TransformColumns(#"Multiplied Column5", {{"2026-27 Forecast", each _ * 1000, Currency.Type}}),
				    #"Multiplied Column7" = Table.TransformColumns(#"Multiplied Column6", {{"2027-28 Forecast", each _ * 1000, Currency.Type}}),
				    #"Multiplied Column8" = Table.TransformColumns(#"Multiplied Column7", {{"2025-26 Target", each _ * 1000, type number}}),
				    #"Multiplied Column9" = Table.TransformColumns(#"Multiplied Column8", {{"2026-27 Target", each _ * 1000, Currency.Type}}),
				    #"Multiplied Column10" = Table.TransformColumns(#"Multiplied Column9", {{"2027-28 Target", each _ * 1000, Currency.Type}}),
				    // New line creation with all table lines
				
				    NewLine = Record.FromList(
				        {"Pending"} & List.Repeat({null}, Table.ColumnCount(#"Multiplied Column10") - 1),
				        Table.ColumnNames(#"Multiplied Column10")
				    ),
				
				   
				    // Insert new line on the first row
				    #"InsertRow" = Table.InsertRows(#"Multiplied Column10", 0, {NewLine}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(InsertRow, {"Capital Project/Program by Name", "Funding Classification"}, "Attribute", "Value"),
				    #"Split Column by Delimiter" = Table.SplitColumn(#"Unpivoted Columns", "Attribute", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Attribute.1", "Attribute.2"}),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Split Column by Delimiter",{{"Attribute.1", type text}, {"Attribute.2", type text}, {"Value", Currency.Type}}),
				    #"Pivoted Column" = Table.Pivot(#"Changed Type2", List.Distinct(#"Changed Type2"[Attribute.2]), "Attribute.2", "Value", List.Sum),
				    #"Renamed Columns1" = Table.RenameColumns(#"Pivoted Column",{{"Attribute.1", "Fiscal Year"}}),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Renamed Columns1",{{"Forecast", Currency.Type}, {"Target", Currency.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type3", "Accum", each if [Fiscal Year] = "2025-26" then #date(2025, 1, 1) else if [Fiscal Year] = "2026-27" then #date(2026, 1, 1) else if [Fiscal Year] = "2027-28" then #date(2027, 1, 1) else if [Fiscal Year] = "Extra-20%" then #date(2028, 1, 1) else ""),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom",{{"Accum", type date}})
				in
				    #"Changed Type4"
				```

	annotation PBI_ResultType = Table

